"""Calendar feed — Aman's dated obligations as one iCalendar URL his phone subscribes to. No OAuth, zero LLM spend.

GET /api/calendar.ics?token=<CALENDAR_TOKEN> (also header X-Calendar-Token) returns text/calendar with:
  - every compliance due date in the next 365 days (mdo_compliance.upcoming — the statutory calendar × the
    entity list, group-level until the CoS loads compliance_entities): SUMMARY "<item> — <entity or group>",
    two VALARMs (7 days and 1 day before, Aman's "at least a week before");
  - every option / future expiry in share_master_positions (instrument parsed by mdo_share_master.parse_instrument);
  - the NIFTY option alert rows (option_levels) as a dated note on their expiry;
  - the Las Vegas trip, 10–12 Nov 2026, dates only, read from briefs/TRIP_LAS_VEGAS_2026-11.md (never the prices).
Computed on request — no bot, no table. The token is its own door (CALENDAR_TOKEN in .env, generated by
deploy_vps.sh when empty, printed in its summary): the app key never travels in a calendar URL, and the feed
answers 403 to everyone while the token is empty. The auth middleware exempts the path; Caddy proxies /api/*.
The pure helpers above register() take plain values and touch nothing — tests/test_calendar.py runs them.
"""
from __future__ import annotations

import hashlib
import hmac
import os
import re
from datetime import date, datetime, timedelta, timezone
from typing import Any, Awaitable, Callable

from fastapi import Request

from mdo_cos import IST

FEED_PATH = "/api/calendar.ics"
HORIZON_DAYS = 365
PRODID = "-//MDO Chief of Staff//Calendar feed//EN"
CAL_NAME = "MDO — Aman"
TRIP_BRIEF = os.environ.get("TRIP_BRIEF_PATH", os.path.join(os.path.dirname(os.path.abspath(__file__)), "briefs", "TRIP_LAS_VEGAS_2026-11.md"))
MONTHS = {m: i for i, m in enumerate(("jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"), 1)}
_TRIP_DATES = re.compile(r"(\d{1,2})\s*[–\-]\s*(\d{1,2})\s+([A-Za-z]{3})[a-z]*\s+(\d{4})")


# ── pure helpers ──────────────────────────────────────────────────────────────
def ics_escape(s: Any) -> str:
    return (str(s or "").replace("\\", "\\\\").replace("\r\n", "\n").replace("\r", "\n")
            .replace("\n", "\\n").replace(";", "\\;").replace(",", "\\,"))


def fold(line: str) -> str:
    """RFC 5545 §3.1: lines ≤ 75 octets, continuation lines start with one space. Splits on UTF-8 boundaries."""
    raw = line.encode("utf-8")
    if len(raw) <= 75:
        return line
    out, cur = [], b""
    for ch in line:
        b = ch.encode("utf-8")
        limit = 75 if not out else 74
        if len(cur) + len(b) > limit:
            out.append(cur)
            cur = b
        else:
            cur += b
    out.append(cur)
    return "\r\n ".join(x.decode("utf-8") for x in out)


def uid_for(*parts: Any) -> str:
    key = "|".join(str(p) for p in parts)
    return hashlib.sha1(key.encode("utf-8")).hexdigest()[:24] + "@mdo.amanagrawal"


def _ymd(d: date | str) -> str:
    d = date.fromisoformat(str(d)[:10]) if not isinstance(d, date) else d
    return d.strftime("%Y%m%d")


def event(uid: str, start: date | str, summary: str, description: str = "", end: date | str | None = None,
          alarms: tuple[str, ...] = (), categories: str = "") -> dict:
    """An all-day event. `end` is the last day (inclusive) — DTEND is exclusive in iCalendar, so +1 day."""
    s = date.fromisoformat(str(start)[:10]) if not isinstance(start, date) else start
    e = (date.fromisoformat(str(end)[:10]) if not isinstance(end, date) else end) if end else s
    return {"uid": uid, "start": s, "end": e + timedelta(days=1), "summary": summary, "description": description,
            "alarms": tuple(alarms), "categories": categories}


def build_ics(events: list[dict], now: datetime | None = None, name: str = CAL_NAME) -> str:
    now = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    stamp = now.strftime("%Y%m%dT%H%M%SZ")
    lines = ["BEGIN:VCALENDAR", "VERSION:2.0", f"PRODID:{PRODID}", "CALSCALE:GREGORIAN", "METHOD:PUBLISH",
             f"X-WR-CALNAME:{ics_escape(name)}", "X-WR-TIMEZONE:Asia/Kolkata"]
    for ev in sorted(events, key=lambda e: (e["start"], e["summary"])):
        lines += ["BEGIN:VEVENT", f"UID:{ev['uid']}", f"DTSTAMP:{stamp}",
                  f"DTSTART;VALUE=DATE:{_ymd(ev['start'])}", f"DTEND;VALUE=DATE:{_ymd(ev['end'])}",
                  f"SUMMARY:{ics_escape(ev['summary'])}"]
        if ev.get("description"):
            lines.append(f"DESCRIPTION:{ics_escape(ev['description'])}")
        if ev.get("categories"):
            lines.append(f"CATEGORIES:{ics_escape(ev['categories'])}")
        lines.append("TRANSP:TRANSPARENT")
        for trig in ev.get("alarms") or ():
            lines += ["BEGIN:VALARM", f"TRIGGER:{trig}", "ACTION:DISPLAY", f"DESCRIPTION:{ics_escape(ev['summary'])}", "END:VALARM"]
        lines.append("END:VEVENT")
    lines.append("END:VCALENDAR")
    return "\r\n".join(fold(l) for l in lines) + "\r\n"


def compliance_events(items: list[dict]) -> list[dict]:
    """One all-day event per occurrence: '<item> — <entity or group>', alarms 7 days + 1 day before."""
    out = []
    for it in items or []:
        targets = [t for t in (it.get("targets") or []) if t]
        who = ", ".join(targets) if targets else str(it.get("group") or "all entities")
        label = str(it.get("label") or it.get("item") or "").strip()
        if not label or not it.get("due"):
            continue
        desc = f"Source: {it.get('source', '')}".strip()
        if it.get("payment"):
            desc += "\nPayment — your click (Directive 4)."
        if it.get("extendable"):
            desc += "\nDate can move by notification; the statutory date stands until the CA says otherwise."
        out.append(event(uid_for("compliance", it.get("item_id"), it["due"], who), it["due"], f"{label} — {who}", desc,
                         alarms=("-P7D", "-P1D"), categories="Compliance"))
    return out


def position_expiry_events(positions: list[dict]) -> list[dict]:
    """share_master_positions rows that carry an expiry (options and futures): 'Expiry: <instrument> (<account>)'."""
    out, seen = [], set()
    for p in positions or []:
        exp = p.get("expiry")
        if not exp:
            continue
        key = (p.get("account"), p.get("instrument"))
        if key in seen:
            continue
        seen.add(key)
        qty = p.get("qty")
        desc = f"{p.get('side', '')} {qty if qty is not None else '?'} · {p.get('product') or ''} · account {p.get('account')}".strip()
        out.append(event(uid_for("expiry", p.get("account"), p.get("instrument")), exp,
                         f"Expiry: {p.get('instrument')} ({p.get('account')})", desc, alarms=("-P1D",), categories="Positions"))
    return out


def option_alert_events(rows: list[dict]) -> list[dict]:
    """The option_levels alert rows (NIFTY 29-Dec-26 25000 CE below 30, A24) as a dated note on their expiry."""
    out = []
    for r in rows or []:
        if not r.get("active", 1):
            continue
        exp = r.get("expiry_iso") or r.get("expiry")
        d = _expiry_date(exp)
        if d is None:
            continue
        rule = []
        if r.get("alert_below") is not None:
            rule.append(f"below {r['alert_below']:g}")
        if r.get("alert_above") is not None:
            rule.append(f"above {r['alert_above']:g}")
        held = str(r.get("held") or "").strip() or "nobody"
        desc = f"Alert rule: {' / '.join(rule) or 'none'} · held: {held}" + (f"\n{r['note']}" if r.get("note") else "")
        out.append(event(uid_for("option-alert", r.get("instrument")), d, f"Note: option alert {r.get('instrument')} ({' / '.join(rule) or 'no rule'})",
                         desc, categories="Options"))
    return out


def _expiry_date(s: Any) -> date | None:
    """'29-Dec-2026' (NSE spelling) / '29-Dec-26' / ISO → date."""
    s = str(s or "").strip()
    if not s:
        return None
    try:
        return date.fromisoformat(s[:10])
    except ValueError:
        pass
    m = re.match(r"^(\d{1,2})-([A-Za-z]{3})-(\d{2}|\d{4})$", s)
    if not m or m.group(2).lower() not in MONTHS:
        return None
    y = int(m.group(3))
    y = y + 2000 if y < 100 else y
    try:
        return date(y, MONTHS[m.group(2).lower()], int(m.group(1)))
    except ValueError:
        return None


def trip_dates_from_brief(text: str) -> tuple[date, date] | None:
    """'# Las Vegas trip — provisional, 10–12 Nov 2026' → (2026-11-10, 2026-11-12). Dates only, nothing else is read."""
    for line in (text or "").splitlines():
        if not line.startswith("#"):
            continue
        m = _TRIP_DATES.search(line)
        if m and m.group(3).lower() in MONTHS:
            y, mo = int(m.group(4)), MONTHS[m.group(3).lower()]
            try:
                return date(y, mo, int(m.group(1))), date(y, mo, int(m.group(2)))
            except ValueError:
                return None
    return None


def trip_events(path: str = TRIP_BRIEF) -> list[dict]:
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return []
    span = trip_dates_from_brief(text)
    if not span:
        return []
    return [event(uid_for("trip", "las-vegas", span[0]), span[0], "Las Vegas trip (provisional)",
                  f"Dates from briefs/{os.path.basename(path)}; visa and bookings are your click.", end=span[1],
                  alarms=("-P7D",), categories="Travel")]


def token_ok(supplied: str, expected: str) -> bool:
    return bool(expected) and bool(supplied) and hmac.compare_digest(str(supplied), str(expected))


# ── registration ──────────────────────────────────────────────────────────────
def register(app, vdb: Callable[[], Awaitable[Any]], compliance: dict, share_master_module=None) -> dict:
    from starlette.responses import JSONResponse, Response

    async def positions_rows(now: datetime) -> list[dict]:
        db = await vdb()
        rows = [dict(r) for r in await db.execute_fetchall(
            "SELECT account, instrument, side, qty, product FROM share_master_positions ORDER BY account, instrument")]
        if share_master_module is None:
            return []
        return share_master_module.position_rows(rows, now)

    async def option_rows() -> list[dict]:
        db = await vdb()
        have = await db.execute_fetchall("SELECT name FROM sqlite_master WHERE type='table' AND name='option_levels'")
        if not have:
            return []
        return [dict(r) for r in await db.execute_fetchall(
            "SELECT instrument, expiry, alert_below, alert_above, note, held, active FROM option_levels ORDER BY instrument")]

    async def events(now: datetime | None = None) -> list[dict]:
        now = (now or datetime.now(IST)).astimezone(IST)
        comp = await compliance["upcoming"](HORIZON_DAYS, now)
        evs = compliance_events(comp.get("items") or [])
        evs += position_expiry_events(await positions_rows(now))
        evs += option_alert_events(await option_rows())
        evs += trip_events()
        return evs

    async def feed_text(now: datetime | None = None) -> str:
        return build_ics(await events(now), now)

    @app.get(FEED_PATH)
    async def calendar_ics(request: Request, token: str = ""):
        expected = os.environ.get("CALENDAR_TOKEN", "").strip()
        if not expected:
            return JSONResponse({"detail": "calendar feed closed — CALENDAR_TOKEN is empty in .env"}, status_code=403)
        supplied = (token or request.headers.get("x-calendar-token") or "").strip()
        if not token_ok(supplied, expected):
            return JSONResponse({"detail": "unauthorized — ?token=<CALENDAR_TOKEN>"}, status_code=401)
        body = await feed_text()
        return Response(body, media_type="text/calendar; charset=utf-8",
                        headers={"Content-Disposition": 'inline; filename="mdo.ics"', "Cache-Control": "no-store"})

    return {"events": events, "feed_text": feed_text}
